"""
fix_numbering.py  —  restructures chapter/section headings in
create_modified_proposal.py so each Phase gets its own top-level chapter.

NEW structure:
  Chapter 1  : The Invisible Archive          (unchanged)
  Chapter 2  : Build Pipeline Overview        (intro + pipeline table only)
  Chapter 3  : Phase 1 — Scan & Extract
  Chapter 4  : Phase 2 — Index & Embed
  Chapter 5  : Phase 3 — Fine-Tune, Merge & Package for BYOM
  Chapter 6  : Phase 4 — Runtime Query via SAP BTP
  Chapter 7  : Governance, Data Protection & Compliance
  Chapter 8  : Sample Code Generated by Claude
  Chapter 9  : RAG-Powered Code Generation Using a Claude Skill
  Chapter 10 : Generating New ABAP Code from Your Training Data
  Chapter 11 : How the Three Knowledge Sources Work Together
"""

import re

SRC = r'c:\Users\ratna\apps\ABAP 2\create_modified_proposal.py'

with open(SRC, 'r', encoding='utf-8') as f:
    src = f.read()

# Each entry: (old_heading_text, old_level, new_heading_text, new_level)
CHANGES = [

    # ── Chapter 2 wrapper ────────────────────────────────────────────────────
    ("Chapter 2:  Build Pipeline \u2014 From Code to Deployed Model", 1,
     "Chapter 2:  Build Pipeline \u2014 All Four Phases at a Glance",  1),

    # ── Phase 1 promoted to Chapter 3 ───────────────────────────────────────
    ("2.2  Phase 1 \u2014 Scan & Extract",                             2,
     "Chapter 3:  Phase 1 \u2014 Scan & Extract",                      1),
    ("2.2.1  How to Run Phase 1",                                       3,
     "3.1  How to Run Phase 1",                                         2),

    # ── Phase 2 promoted to Chapter 4 ───────────────────────────────────────
    ("2.3  Phase 2 \u2014 Index & Embed",                              2,
     "Chapter 4:  Phase 2 \u2014 Index & Embed",                       1),
    ("2.3.1  How to Run Phase 2",                                       3,
     "4.1  How to Run Phase 2",                                         2),

    # ── Phase 3 promoted to Chapter 5 ───────────────────────────────────────
    ("2.4  Phase 3 \u2014 Fine-Tune, Merge and Package for BYOM",      2,
     "Chapter 5:  Phase 3 \u2014 Fine-Tune, Merge and Package for BYOM", 1),
    ("2.4.1  Concept: What Is Fine-Tuning?",                            3,
     "5.1  Concept: What Is Fine-Tuning?",                              2),
    ("2.4.2  Concept: Why QLoRA Instead of Full Fine-Tuning?",          3,
     "5.2  Concept: Why QLoRA Instead of Full Fine-Tuning?",            2),
    ("2.4.3  Step A \u2014 Generate Training Data",                     3,
     "5.3  Step A \u2014 Generate Training Data",                       2),
    ("2.4.4  Step B \u2014 Run QLoRA Fine-Tuning",                      3,
     "5.4  Step B \u2014 Run QLoRA Fine-Tuning",                        2),
    ("2.4.5  Step C \u2014 Merge Adapter into Base Model",              3,
     "5.5  Step C \u2014 Merge Adapter into Base Model",                2),
    ("2.4.6  Step D \u2014 Package as Docker Image (vLLM Format for BYOM)", 3,
     "5.6  Step D \u2014 Package as Docker Image (vLLM Format for BYOM)",   2),
    ("2.4.7  Step E \u2014 Register and Deploy in SAP AI Core (BYOM)", 3,
     "5.7  Step E \u2014 Register and Deploy in SAP AI Core (BYOM)",   2),
    ("2.4.8  How to Run Phase 3",                                       3,
     "5.8  How to Run Phase 3",                                         2),
    ("2.5  Hardware Requirements",                                      2,
     "5.9  Hardware Requirements",                                      2),

    # ── Chapter 3 (Phase 4 / Application) → Chapter 6 ───────────────────────
    ("Chapter 3:  The CodeSage Application",                            1,
     "Chapter 6:  Phase 4 \u2014 Runtime Query via SAP BTP",            1),
    ("3.1  Runtime Architecture",                                       2,
     "6.1  Runtime Architecture",                                       2),
    ("3.2  Developer Query Flow",                                       2,
     "6.2  Developer Query Flow",                                       2),
    ("3.2.1  How to Run Phase 4 \u2014 Deploy the CodeSage Agent",      3,
     "6.3  How to Run Phase 4 \u2014 Deploy the CodeSage Agent",        2),
    ("3.3  Integration Options",                                        2,
     "6.4  Integration Options",                                        2),
    ("3.3.1  SAP Fiori Tile",                                           3,
     "6.4.1  SAP Fiori Tile",                                           3),
    ("3.3.2  Microsoft Teams Bot",                                      3,
     "6.4.2  Microsoft Teams Bot",                                      3),
    ("3.3.3  SAP Joule Integration",                                    3,
     "6.4.3  SAP Joule Integration",                                    3),
    ("3.4  CodeSage Agent \u2014 SAP BTP CAP Service",                  2,
     "6.5  CodeSage Agent \u2014 SAP BTP CAP Service",                  2),

    # ── Chapter 4 → Chapter 7 ────────────────────────────────────────────────
    ("Chapter 4:  Governance, Data Protection & Compliance",            1,
     "Chapter 7:  Governance, Data Protection & Compliance",            1),
    ("4.1  Data Classification & Scan Scope",                           2,
     "7.1  Data Classification & Scan Scope",                           2),
    ("4.2  GDPR & Data Residency",                                      2,
     "7.2  GDPR & Data Residency",                                      2),
    ("4.3  SAP AI Core Compliance Certifications",                      2,
     "7.3  SAP AI Core Compliance Certifications",                      2),
    ("4.4  Access Control & Authentication",                            2,
     "7.4  Access Control & Authentication",                            2),
    ("4.5  Model Governance & Refresh Policy",                          2,
     "7.5  Model Governance & Refresh Policy",                          2),
    ("4.6  Audit Trail & Monitoring",                                   2,
     "7.6  Audit Trail & Monitoring",                                   2),
    ("4.7  Responsible AI Principles",                                  2,
     "7.7  Responsible AI Principles",                                  2),

    # ── Chapter 5 → Chapter 8 ────────────────────────────────────────────────
    ("Chapter 5:  Sample Code Generated by Claude",                     1,
     "Chapter 8:  Sample Code Generated by Claude",                     1),
    ("5.1  Vendor Payment Terms Validator",                             2,
     "8.1  Vendor Payment Terms Validator",                             2),
    ("5.2  ABAP OO Class \u2014 Purchase Order Status Handler",          2,
     "8.2  ABAP OO Class \u2014 Purchase Order Status Handler",          2),
    ("5.3  BAdI Implementation Skeleton",                               2,
     "8.3  BAdI Implementation Skeleton",                               2),
    ("5.4  CDS View with Association",                                  2,
     "8.4  CDS View with Association",                                  2),

    # ── Chapter 6 → Chapter 9 ────────────────────────────────────────────────
    ("Chapter 6:  RAG-Powered Code Generation Using a Claude Skill",    1,
     "Chapter 9:  RAG-Powered Code Generation Using a Claude Skill",    1),
    ("6.1  What Is a Claude Skill?",                                    2,
     "9.1  What Is a Claude Skill?",                                    2),
    ("6.2  RAG + Claude Skill Architecture",                            2,
     "9.2  RAG + Claude Skill Architecture",                            2),
    ("6.3  The Assembled Prompt Structure",                             2,
     "9.3  The Assembled Prompt Structure",                             2),
    ("6.4  Sample Claude Skill Output",                                 2,
     "9.4  Sample Claude Skill Output",                                 2),
    ("6.5  BYOM vs Claude Skill \u2014 When to Use Which",              2,
     "9.5  BYOM vs Claude Skill \u2014 When to Use Which",              2),
    ("6.6  Implementing the Claude Skill in BTP CAP",                   2,
     "9.6  Implementing the Claude Skill in BTP CAP",                   2),
    ("6.7  ChromaDB Collection Strategy for Code Generation",           2,
     "9.7  ChromaDB Collection Strategy for Code Generation",           2),

    # ── Chapter 7 → Chapter 10 ───────────────────────────────────────────────
    ("Chapter 7:  Generating New ABAP Code from Your Training Data",    1,
     "Chapter 10:  Generating New ABAP Code from Your Training Data",   1),
    ("7.1  Q&A Mode vs Code Generation Mode",                           2,
     "10.1  Q&A Mode vs Code Generation Mode",                          2),
    ("7.2  Why Training Data Enables Better Code Generation",           2,
     "10.2  Why Training Data Enables Better Code Generation",          2),
    ("7.3  How Code Generation Works Step by Step",                     2,
     "10.3  How Code Generation Works Step by Step",                    2),
    ("7.4  Example: Generating a Complete ABAP Report",                 2,
     "10.4  Example: Generating a Complete ABAP Report",                2),
    ("7.5  More Generation Examples",                                   2,
     "10.5  More Generation Examples",                                  2),
    ("7.5.1  Generate a Class Method",                                  3,
     "10.5.1  Generate a Class Method",                                 3),
    ("7.5.2  Generate a BAdI Implementation Skeleton",                  3,
     "10.5.2  Generate a BAdI Implementation Skeleton",                 3),
    ("7.5.3  Generate a CDS View",                                      3,
     "10.5.3  Generate a CDS View",                                     3),
    ("7.6  What Makes the Generated Code Safe to Use",                  2,
     "10.6  What Makes the Generated Code Safe to Use",                 2),
    ("7.7  Enabling Code Generation Mode in the CodeSage Agent",        2,
     "10.7  Enabling Code Generation Mode in the CodeSage Agent",       2),
    ("7.8  The Developer Workflow with Code Generation",                2,
     "10.8  The Developer Workflow with Code Generation",               2),

    # ── Chapter 8 → Chapter 11 ───────────────────────────────────────────────
    ("8.1  The Three Knowledge Sources",                                2,
     "11.1  The Three Knowledge Sources",                               2),
    ("8.2  The Query Flow \u2014 Step by Step",                         2,
     "11.2  The Query Flow \u2014 Step by Step",                        2),
    ("8.3  What Each Source Contributes to the Final Answer",           2,
     "11.3  What Each Source Contributes to the Final Answer",          2),
    ("8.3.1  Contribution from the Codebase Model",                     3,
     "11.3.1  Contribution from the Codebase Model",                    3),
    ("8.3.2  Contribution from SAP Help Documentation",                 3,
     "11.3.2  Contribution from SAP Help Documentation",                3),
    ("8.3.3  Contribution from the Cloudification Repository",          3,
     "11.3.3  Contribution from the Cloudification Repository",         3),
    ("8.4  The Final Assembled Answer",                                 2,
     "11.4  The Final Assembled Answer",                                2),
    ("8.5  How Each Source Is Weighted by Query Type",                  2,
     "11.5  How Each Source Is Weighted by Query Type",                 2),
    ("8.6  Keeping the Three Sources Up to Date",                       2,
     "11.6  Keeping the Three Sources Up to Date",                      2),
]

# Chapter 8 title is split across two lines in source — handle separately
ch8_old = ("doc.add_heading('Chapter 8:  How the Codebase, SAP Help, and Cloudification Repository '\n"
           "                'Work Together to Answer a Developer Query', level=1)")
ch8_new = ("doc.add_heading('Chapter 11:  How the Codebase, SAP Help, and Cloudification Repository '\n"
           "                'Work Together to Answer a Developer Query', level=1)")
src = src.replace(ch8_old, ch8_new)

changed = 0
for old_text, old_lvl, new_text, new_lvl in CHANGES:
    old_line = f"doc.add_heading('{old_text}', level={old_lvl})"
    new_line = f"doc.add_heading('{new_text}', level={new_lvl})"
    if old_line in src:
        src = src.replace(old_line, new_line)
        changed += 1
    else:
        print(f"  NOT FOUND: {old_text!r}  (level={old_lvl})")

print(f"Applied {changed} / {len(CHANGES)} heading changes.")

with open(SRC, 'w', encoding='utf-8') as f:
    f.write(src)

print("Done. create_modified_proposal.py updated.")
